#
# Module manifest for module 'Hook'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 05/08/2020
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Hook.psm1'

    # Version number of this module.
    ModuleVersion = '$version$'

    # ID used to uniquely identify this module
    GUID = '02e62631-d583-42de-9cf0-1effd4506a84'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2020 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'A Cross-Platform PowerShell module for creating hooks and event driven actions'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @(
        'System.Web',
        'System.Net.Http'
    )

    # Functions to export from this Module
    FunctionsToExport = @(
        'Start-Hook',
        'Register-HookEvent',
        'New-HookTrigger',
        'New-HookAction'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'hook', 'events', 'actions', 'trigger', 'listener',
                'powershell-core', 'windows', 'unix', 'linux', 'PSEdition_Core', 'cross-platform')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/Hook/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/Hook'

            # Release notes for this particular version of the module
            ReleaseNotes = 'https://github.com/Badgerati/Hook/releases/tag/v$version$'

        }
    }
}